export const FETCH_JOBS_REQUEST = 'FETCH_JOBS_REQUEST';
export const FETCH_JOBS_SUCCESS = 'FETCH_JOBS_SUCCESS';
export const FETCH_JOBS_FAILURE = 'FETCH_JOBS_FAILURE';
export const APPLY_FILTERS = 'APPLY_FILTERS';
export const LOAD_MORE_JOBS_REQUEST = 'LOAD_MORE_JOBS_REQUEST';
export const LOAD_MORE_JOBS_SUCCESS = 'LOAD_MORE_JOBS_SUCCESS';
export const LOAD_MORE_JOBS_FAILURE = 'LOAD_MORE_JOBS_FAILURE';
